# Project specific config
language: generic

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable

    - os: linux
      env: ATOM_CHANNEL=beta

deploy:
  provider: apm
  api_key:
    secure: "MvxKJAUglt0zbMBMOEaJFwqK8ptYlJD1mSyTNZ7x0T02CdST4Fx70AK3x79odI0o8YUGrLKfFdJyBrGkme9ainYDeomIu0O4QTZ2tGdpLsbTop4dDnQbYjyba/gI6aK+4x9WJ167CY3bYLs+0w3P4HMhtvsvQuLAhpZqbZykOgQ="
  edge:
    source: kepler0/dpl
    branch: apm
  on:
    tags: true

# Generic setup follows
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
