script: './build-packages.sh'

git:
  depth: 10

sudo: false

os:
  - linux

env:
  global:
    - INSTALL_PACKAGES="Hydrogen"
    - secure: ruvrQ1I66tqYPDjbShFZEe5SkCjXu13bSTR3RP52O/MQ481N+KVIxuTv7GwEhyOcN3awRp3d3jHcbXZPZJBOGkyJxaWPiS1GEvyM5LHx8XJNT+/Uo4ViETLa4VeRXIGPmGnMJmOFtLYkelSIgak6Y0iuM2EwH2bfepqMNBfjM54=

  matrix:
    - ATOM_CHANNEL=stable

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - zeromq-dev
    - fakeroot
