dist: trusty
sudo: false
language: javascript
script: "./build-packages.sh"
git:
  depth: 10
branches:
  only:
  - master
os:
- linux
env:
  matrix:
  - ATOM_CHANNEL=stable
  global:
    secure: y12pFbEgoZiTWzxhNeGx/TNC+3xGCyn8mvizfecUsMcJ8vHILyZrVisDRibD38L74zmHM00BUXHWJaqYcsVlhRh1W32E4Qsd4CkrSBdpTjV272u1CIJvho0RLH2GKGFN5tQKkhbheKFfTahNoTUUuwLqvMEcvQUgW5NvYZO2XRc9Wy2j6A8wLWxFDAKslRLfCC+pgLmejmX7EB4Vg3u12xOz/wSeH4b931b/9q9qTOfWkQFhvmuN1SW6yiZPk0gLzYXioU8oRIUXb/ytJ4zfcQnOxjqEZkESPMGxNwJOeZKw2Vc0CX0dg+8N67t3XiVDt+GJY6lByXzMGy6XiOS4nGvhaH1Z6gZ3sBNHNIBEhnOFTUUrgBngaViXFfDJEaHnXBZT+YEZ6bCfJTLr7pNCJgUs9Vuxfg67RzhwV2Y3zNUCYCUezMQ3leLUnZyU5eCcbpnB1iVaWQTafYPhCwf3y/UhQheCoRMGum48UCsX8bGWBl4l242tYM3bfbCJNFEDkMVKHI2URz/5BCMPG9cVNXAOY0tTB3TEsWzVu5M9E5h+A/QGQAruc3x+edoRxv8JOP8j4rMieqXsd0rYvi4PEOEKvSac35NWG4nF+3kWwA05rO0pviQv9MX7nwT1SCMkaWZg+SJNRMTBrmwbJYfc858cdZO0bjARZnU/SrnTkfw=
addons:
  apt:
    packages:
    - build-essential
    - git
    - fakeroot
    - libzmq3-dev
